/* GOSM - the Gtk OpenStreetMap Tool
 *
 * Copyright (C) 2009  Sebastian Kuerten
 *
 * This file is part of Gosm.
 *
 * Gosm is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Gosm is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Gosm.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include <glib.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>

#include "menu.h"
#include "about/about.h"
#include "manual/manual.h"
#include "config/config.h"
#include "config/config_widget.h"

G_DEFINE_TYPE (Menu, menu, GTK_TYPE_MENU_BAR);

/*enum
{
        SIGNAL_NAME_1,
        SIGNAL_NAME_n,
        LAST_SIGNAL
};*/

//static guint menu_signals[LAST_SIGNAL] = { 0 };
//g_signal_emit (widget, menu_signals[SIGNAL_NAME_n], 0);


static gboolean exit_cb(GtkWidget *widget);
static gboolean button_zoom_in_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean button_zoom_out_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean button_move_up_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean button_move_down_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean button_move_left_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean button_move_right_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean menubar_fullscreen_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean show_manual_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean show_about_gosm_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean show_about_osm_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean show_about_nf_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean show_about_license_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean show_preferences_cb(GtkWidget *widget, gpointer menubar_p);
static gboolean preferences_confirm_cb(GtkWidget * widget, ConfigWidget * conf_widget);
static gboolean preferences_cancel_cb(GtkWidget * widget, GtkWindow *window);

static gboolean window_event_cb(GtkWidget *window, GdkEventWindowState *event, gpointer menubar_p);

GtkWidget * menu_new(GtkWindow * main_window, MapArea * map_area, Config * config)
{
	Menu * menubar = g_object_new(GOSM_TYPE_MENU, NULL);
	menubar -> main_window = main_window;
	menubar -> map_area = map_area;
	menubar -> config = config;
	/********************************************************************************************
	* the following part is autogenerated; to regenerate, type:
	* :r !./misc/menu_gen.py 2 misc/Menu.txt
	********************************************************************************************/
	GtkWidget *item_1                      = gtk_menu_item_new_with_label("File");
	GtkWidget *menu_1                      = gtk_menu_new();
	GtkWidget *item_1_1                    = gtk_menu_item_new_with_label("Quit");
	GtkWidget *item_2                      = gtk_menu_item_new_with_label("View");
	GtkWidget *menu_2                      = gtk_menu_new();
	GtkWidget *item_2_1                    = gtk_check_menu_item_new_with_label("Fullscreen");
	GtkWidget *item_2_2                    = gtk_menu_item_new_with_label("Control");
	GtkWidget *menu_2_2                    = gtk_menu_new();
	GtkWidget *item_2_2_1                  = gtk_menu_item_new_with_label("Zoom In");
	GtkWidget *item_2_2_2                  = gtk_menu_item_new_with_label("Zoom Out");
	GtkWidget *item_2_2_3                  = gtk_menu_item_new_with_label("Move Up");
	GtkWidget *item_2_2_4                  = gtk_menu_item_new_with_label("Move Down");
	GtkWidget *item_2_2_5                  = gtk_menu_item_new_with_label("Move Left");
	GtkWidget *item_2_2_6                  = gtk_menu_item_new_with_label("Move Right");
	GtkWidget *item_2_3                    = gtk_menu_item_new_with_label("Tiles");
	GtkWidget *menu_2_3                    = gtk_menu_new();
	GtkWidget *item_2_3_1                  = gtk_radio_menu_item_new_with_label(NULL, "Mapnik");
	GtkWidget *item_2_3_2                  = gtk_radio_menu_item_new_with_label(gtk_radio_menu_item_get_group((GtkRadioMenuItem*)item_2_3_1), "Osmarender");
	GtkWidget *item_2_3_3                  = gtk_radio_menu_item_new_with_label(gtk_radio_menu_item_get_group((GtkRadioMenuItem*)item_2_3_1), "OpenAerial");
	GtkWidget *item_2_3_4                  = gtk_radio_menu_item_new_with_label(gtk_radio_menu_item_get_group((GtkRadioMenuItem*)item_2_3_1), "Google");
	GtkWidget *item_2_3_5                  = gtk_radio_menu_item_new_with_label(gtk_radio_menu_item_get_group((GtkRadioMenuItem*)item_2_3_1), "Yahoo");
	GtkWidget *item_3                      = gtk_menu_item_new_with_label("Selection");
	GtkWidget *menu_3                      = gtk_menu_new();
	GtkWidget *item_3_1                    = gtk_check_menu_item_new_with_label("Snap to Map");
	GtkWidget *item_3_2                    = gtk_check_menu_item_new_with_label("Hide");
	GtkWidget *item_3_3                    = gtk_menu_item_new_with_label("Export");
	GtkWidget *item_3_4                    = gtk_menu_item_new_with_label("Download");
	GtkWidget *item_4                      = gtk_menu_item_new_with_label("Options");
	GtkWidget *menu_4                      = gtk_menu_new();
	GtkWidget *item_4_1                    = gtk_menu_item_new_with_label("Preferences");
	GtkWidget *item_5                      = gtk_menu_item_new_with_label("Help");
	GtkWidget *menu_5                      = gtk_menu_new();
	GtkWidget *item_5_1                    = gtk_menu_item_new_with_label("Manual");
	GtkWidget *item_5_2                    = gtk_menu_item_new_with_label("About GOsmView");
	GtkWidget *item_5_3                    = gtk_menu_item_new_with_label("About OpenStreetMap");
	GtkWidget *item_5_4                    = gtk_menu_item_new_with_label("About Namefinder");
	GtkWidget *item_5_5                    = gtk_menu_item_new_with_label("License");
	gtk_menu_item_set_submenu(GTK_MENU_ITEM(item_1),              menu_1);
	gtk_menu_item_set_submenu(GTK_MENU_ITEM(item_2),              menu_2);
	gtk_menu_item_set_submenu(GTK_MENU_ITEM(item_2_2),            menu_2_2);
	gtk_menu_item_set_submenu(GTK_MENU_ITEM(item_2_3),            menu_2_3);
	gtk_menu_item_set_submenu(GTK_MENU_ITEM(item_3),              menu_3);
	gtk_menu_item_set_submenu(GTK_MENU_ITEM(item_4),              menu_4);
	gtk_menu_item_set_submenu(GTK_MENU_ITEM(item_5),              menu_5);
	gtk_menu_shell_append(GTK_MENU_SHELL(menubar),            item_1);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_1),             item_1_1);
	gtk_menu_shell_append(GTK_MENU_SHELL(menubar),            item_2);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2),             item_2_1);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2),             item_2_2);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2_2),           item_2_2_1);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2_2),           item_2_2_2);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2_2),           item_2_2_3);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2_2),           item_2_2_4);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2_2),           item_2_2_5);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2_2),           item_2_2_6);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2),             item_2_3);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2_3),           item_2_3_1);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2_3),           item_2_3_2);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2_3),           item_2_3_3);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2_3),           item_2_3_4);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_2_3),           item_2_3_5);
	gtk_menu_shell_append(GTK_MENU_SHELL(menubar),            item_3);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_3),             item_3_1);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_3),             item_3_2);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_3),             item_3_3);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_3),             item_3_4);
	gtk_menu_shell_append(GTK_MENU_SHELL(menubar),            item_4);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_4),             item_4_1);
	gtk_menu_shell_append(GTK_MENU_SHELL(menubar),            item_5);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_5),             item_5_1);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_5),             item_5_2);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_5),             item_5_3);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_5),             item_5_4);
	gtk_menu_shell_append(GTK_MENU_SHELL(menu_5),             item_5_5);
	menubar -> menu_file_quit                 = item_1_1;
	menubar -> menu_view_fullscreen           = item_2_1;
	menubar -> menu_control_zoom_in           = item_2_2_1;
	menubar -> menu_control_zoom_out          = item_2_2_2;
	menubar -> menu_control_move_up           = item_2_2_3;
	menubar -> menu_control_move_down         = item_2_2_4;
	menubar -> menu_control_move_left         = item_2_2_5;
	menubar -> menu_control_move_right        = item_2_2_6;
	menubar -> menu_tiles_mapnik              = item_2_3_1;
	menubar -> menu_tiles_osmarender          = item_2_3_2;
	menubar -> menu_tiles_openaerial          = item_2_3_3;
	menubar -> menu_tiles_google              = item_2_3_4;
	menubar -> menu_tiles_yahoo               = item_2_3_5;
	menubar -> menu_selection_snap            = item_3_1;
	menubar -> menu_selection_show            = item_3_2;
	menubar -> menu_selection_export          = item_3_3;
	menubar -> menu_selection_download        = item_3_4;
	menubar -> menu_options_preferences       = item_4_1;
	menubar -> menu_help_manual               = item_5_1;
	menubar -> menu_help_about_gosm           = item_5_2;
	menubar -> menu_help_about_osm            = item_5_3;
	menubar -> menu_help_about_nf             = item_5_4;
	menubar -> menu_help_license              = item_5_5;
	/********************************************************************************************
	* end auto-generated part
	********************************************************************************************/

	gtk_widget_set_sensitive(menubar -> menu_tiles_osmarender, FALSE);
	gtk_widget_set_sensitive(menubar -> menu_tiles_openaerial, FALSE);
	gtk_widget_set_sensitive(menubar -> menu_tiles_google, FALSE);
	gtk_widget_set_sensitive(menubar -> menu_tiles_yahoo, FALSE);

	/********************************************************************************************
	* signals 
	********************************************************************************************/
	g_signal_connect(
		G_OBJECT(menubar -> menu_file_quit), "activate",
		G_CALLBACK(exit_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_options_preferences), "activate", 
		G_CALLBACK(show_preferences_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_help_manual), "activate", 
		G_CALLBACK(show_manual_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_help_about_gosm), "activate", 
		G_CALLBACK(show_about_gosm_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_help_about_osm), "activate", 
		G_CALLBACK(show_about_osm_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_help_about_nf), "activate", 
		G_CALLBACK(show_about_nf_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_help_license),	"activate", 
		G_CALLBACK(show_about_license_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_control_zoom_in), "activate", 
		G_CALLBACK(button_zoom_in_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_control_zoom_out), "activate", 
		G_CALLBACK(button_zoom_out_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_control_move_up), "activate", 
		G_CALLBACK(button_move_up_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_control_move_down), "activate", 
		G_CALLBACK(button_move_down_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_control_move_left), "activate", 
		G_CALLBACK(button_move_left_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_control_move_right), "activate", 
		G_CALLBACK(button_move_right_cb), (gpointer)menubar);
	g_signal_connect(
		G_OBJECT(menubar -> menu_view_fullscreen), "toggled", 
		G_CALLBACK(menubar_fullscreen_cb), (gpointer)menubar);

	/* notice when window is being fullscreened */
	g_signal_connect(
		G_OBJECT(main_window), "window-state-event", 
		G_CALLBACK(window_event_cb), (gpointer)menubar);
	return GTK_WIDGET(menubar);
}

static void menu_class_init(MenuClass *class)
{
        /*menu_signals[SIGNAL_NAME_n] = g_signal_new(
                "signal-name-n",
                G_OBJECT_CLASS_TYPE (class),
                G_SIGNAL_RUN_FIRST,
                G_STRUCT_OFFSET (MenuClass, function_name),
                NULL, NULL,
                g_cclosure_marshal_VOID__VOID,
                G_TYPE_NONE, 0);*/
}

static void menu_init(Menu *menu)
{
}

static gboolean exit_cb(GtkWidget *widget)
{
	exit(0);
}

/****************************************************************************************************
* zoom in / out
****************************************************************************************************/
static gboolean button_zoom_in_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	map_area_zoom_in(menubar -> map_area);
}
static gboolean button_zoom_out_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	map_area_zoom_out(menubar -> map_area);
}

/****************************************************************************************************
* map moving
****************************************************************************************************/
static gboolean button_move_up_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	map_area_move(menubar -> map_area, DIRECTION_TOP);
}
static gboolean button_move_down_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	map_area_move(menubar -> map_area, DIRECTION_DOWN);
}
static gboolean button_move_left_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	map_area_move(menubar -> map_area, DIRECTION_LEFT);
}
static gboolean button_move_right_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	map_area_move(menubar -> map_area, DIRECTION_RIGHT);
}

/****************************************************************************************************
* toggle fullscreen
****************************************************************************************************/
static gboolean menubar_fullscreen_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(menubar -> menu_view_fullscreen))){
		gdk_window_fullscreen(GTK_WIDGET(menubar -> main_window) -> window);
	}else{
		gdk_window_unfullscreen(GTK_WIDGET(menubar -> main_window) -> window);
	}
}

/****************************************************************************************************
* dialogs
****************************************************************************************************/
static gboolean show_manual_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	GtkWidget * manual_win = manual_dialog_new(menubar -> main_window);
	gtk_widget_show_all(manual_win);
}

static gboolean show_about_gosm_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	GtkWidget * about_win = about_dialog_new(menubar -> main_window, menubar -> map_area);
	gtk_widget_show_all(about_win);
	gtk_notebook_set_current_page(about_dialog_get_notebook(GOSM_ABOUT_DIALOG(about_win)), 0);
}
static gboolean show_about_osm_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	GtkWidget * about_win = about_dialog_new(menubar -> main_window, menubar -> map_area);
	gtk_widget_show_all(about_win);
	gtk_notebook_set_current_page(about_dialog_get_notebook(GOSM_ABOUT_DIALOG(about_win)), 1);
}
static gboolean show_about_nf_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	GtkWidget * about_win = about_dialog_new(menubar -> main_window, menubar -> map_area);
	gtk_widget_show_all(about_win);
	gtk_notebook_set_current_page(about_dialog_get_notebook(GOSM_ABOUT_DIALOG(about_win)), 2);
}
static gboolean show_about_license_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	GtkWidget * about_win = about_dialog_new(menubar -> main_window, menubar -> map_area);
	gtk_widget_show_all(about_win);
	gtk_notebook_set_current_page(about_dialog_get_notebook(GOSM_ABOUT_DIALOG(about_win)), 3);
}
static gboolean show_preferences_cb(GtkWidget *widget, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	ConfigWidget * config_widget = GOSM_CONFIG_WIDGET(config_widget_new(menubar -> config));
	config_widget_show_in_window(config_widget, menubar -> main_window);
}

/****************************************************************************************************
* the events of the main window
* used to keep the "fullscreen"-checkbox up-to-date
****************************************************************************************************/
static gboolean window_event_cb(GtkWidget *window, GdkEventWindowState *event, gpointer menubar_p)
{
	Menu * menubar = GOSM_MENU(menubar_p);
	if ((event -> changed_mask & GDK_WINDOW_STATE_FULLSCREEN) != 0){
		gboolean fullscreened = 
			(gdk_window_get_state(GTK_WIDGET(menubar -> main_window) -> window)
				& GDK_WINDOW_STATE_FULLSCREEN) != 0;
		gtk_check_menu_item_set_active(GTK_CHECK_MENU_ITEM(menubar -> menu_view_fullscreen), fullscreened);
	}
}
